### ISSUE TITLE
MakeBigWig Issue

### ISSUE THREAD

**Issue by phoebe460** [Taiji-pipeline/Taiji#15]
Hi Kai,

So I've decided to make a new input file, but now starting from my .BAM files with the tag 'PairedEnd' and same RNA quantification files like before. I've been running into the following error when trying to make BigWig files:

<img width="1396" alt="Error 4" src="https://user-images.githubusercontent.com/56165012/103783849-12229880-4fee-11eb-9852-8a85a5a4a8d1.png">

Do you know how to resolve this? I've placed the libssl.so.1.0.0 in my $PATH directory -> /.local/bin and I am still getting the same error. Any insights regarding this? Any help would be much appreciated again! Thank you!

**Comment by phoebe460** [comment]
As followup from discussion on Slack: 

<img width="1094" alt="Slack Discussion 1" src="https://user-images.githubusercontent.com/56165012/103794547-b100c200-4ff9-11eb-927a-c02cea43838a.png">


Here is my input file after making the changes.

```
RNA-seq:
  - group: 'NDC'
    id: 'NDC_RNA'
    replicates:
      - rep: 1
        files:
          #Customized gene expression file
          - path: /home/prvaldes/scratch/Taiji/RNA-seq-counts/RNA-seq-counts_Taiji_NDC-1.tsv
            tags: ['GeneQuant']
      - rep: 2
        files:
          #Customized gene expression file
          - path: /home/prvaldes/scratch/Taiji/RNA-seq-counts/RNA-seq-counts_Taiji_NDC-2.tsv
            tags: ['GeneQuant']
      - rep: 3
        files:
          #Customized gene expression file
          - path: /home/prvaldes/scratch/Taiji/RNA-seq-counts/RNA-seq-counts_Taiji_NDC-3.tsv
            tags: ['GeneQuant']
  - group: 'V717I'
    id: 'V717I_RNA'
    replicates:
      - rep: 1
        files:
          #Customized gene expression file
          - path: /home/prvaldes/scratch/Taiji/RNA-seq-counts/RNA-seq-counts_Taiji_V717I-1.tsv
            tags: ['GeneQuant']
      - rep: 2
        files:
          #Customized gene expression file
          - path: /home/prvaldes/scratch/Taiji/RNA-seq-counts/RNA-seq-counts_Taiji_V717I-2.tsv
            tags: ['GeneQuant']
      - rep: 3
        files:
          #Customized gene expression file                                                     
          - path: /home/prvaldes/scratch/Taiji/RNA-seq-counts/RNA-seq-counts_Taiji_V717I-3.tsv                            
            tags: ['GeneQuant']
  - group: 'A79V'
    id: 'A79V_RNA'
    replicates:
      - rep: 1
        files:
          #Customized gene expression file
          - path: /home/prvaldes/scratch/Taiji/RNA-seq-counts/RNA-seq-counts_Taiji_A79V-1.tsv
            tags: ['GeneQuant']
      - rep: 2
        files:
          #Customized gene expression file
          - path: /home/prvaldes/scratch/Taiji/RNA-seq-counts/RNA-seq-counts_Taiji_A79V-2.tsv
            tags: ['GeneQuant']
      - rep: 3
        files:
          #Customized gene expression file                                                     
          - path: /home/prvaldes/scratch/Taiji/RNA-seq-counts/RNA-seq-counts_Taiji_A79V-3.tsv                            
            tags: ['GeneQuant']
  - group: 'N141I'
    id: 'N141I_RNA'
    replicates:
      - rep: 1
        files:
          #Customized gene expression file
          - path: /home/prvaldes/scratch/Taiji/RNA-seq-counts/RNA-seq-counts_Taiji_N141I-1.tsv
            tags: ['GeneQuant']
      - rep: 2
        files:
          #Customized gene expression file
          - path: /home/prvaldes/scratch/Taiji/RNA-seq-counts/RNA-seq-counts_Taiji_N141I-2.tsv
            tags: ['GeneQuant']
      - rep: 3
        files:
          #Customized gene expression file                                                     
          - path: /home/prvaldes/scratch/Taiji/RNA-seq-counts/RNA-seq-counts_Taiji_N141I-3.tsv                            
            tags: ['GeneQuant']

ATAC-seq:
  - group: 'NDC'
    id: 'NDC_ATAC'
    replicates:
      - rep: 1
        files: 
        - path: /home/prvaldes/scratch/diffTF/input/data/bam/NDC_1.bam
          tags: ['PairedEnd', 'Filtered']
      - rep: 2
        files: 
        - path: /home/prvaldes/scratch/diffTF/input/data/bam/NDC_2.bam
          tags: ['PairedEnd', 'Filtered']
      - rep: 3
        files: 
        - path: /home/prvaldes/scratch/diffTF/input/data/bam/NDC_3.bam
          tags: ['PairedEnd', 'Filtered']
  - group: 'V717I'
    id: 'V717I_ATAC'
    replicates:
      - rep: 1
        files: 
        - path: /home/prvaldes/scratch/diffTF/input/data/bam/V717I_1.bam
          tags: ['PairedEnd', 'Filtered']
      - rep: 2
        files: 
        - path: /home/prvaldes/scratch/diffTF/input/data/bam/V717I_2.bam
          tags: ['PairedEnd', 'Filtered']  
      - rep: 3
        files: 
        - path: /home/prvaldes/scratch/diffTF/input/data/bam/V717I_3.bam
          tags: ['PairedEnd', 'Filtered'] 
  - group: 'A79V'
    id: 'A79V_ATAC'
    replicates:
      - rep: 1
        files: 
        - path: /home/prvaldes/scratch/diffTF/input/data/bam/A79V_1.bam
          tags: ['PairedEnd', 'Filtered']
      - rep: 2
        files: 
        - path: /home/prvaldes/scratch/diffTF/input/data/bam/A79V_2.bam
          tags: ['PairedEnd', 'Filtered']  
      - rep: 3
        files: 
        - path: /home/prvaldes/scratch/diffTF/input/data/bam/A79V_3.bam
          tags: ['PairedEnd', 'Filtered'] 
  - group: 'N141I'
    id: 'N141I_ATAC'
    replicates:
      - rep: 1
        files: 
        - path: /home/prvaldes/scratch/diffTF/input/data/bam/N141I_1.bam
          tags: ['PairedEnd', 'Filtered']
      - rep: 2
        files: 
        - path: /home/prvaldes/scratch/diffTF/input/data/bam/N141I_2.bam
          tags: ['PairedEnd', 'Filtered']
      - rep: 3
        files: 
        - path: /home/prvaldes/scratch/diffTF/input/data/bam/N141I_3.bam
          tags: ['PairedEnd', 'Filtered'] 
```

So far, no errors when running with the new input file, so will keep you updated if I run into other issues. Thanks again!
