### ISSUE TITLE
Problem running Taiji

### ISSUE THREAD

**Issue by BW15061999** [Taiji-pipeline/Taiji#24]
Hi,
when I try to run Taiji, it generate error 
`taiji: Must contain exactly 1 file`
`CallStack (from HasCallStack):error, called at app/Main.hs:107:1 in main:Main`

I don't know how to deal with it. Thank you!

**Comment by kaizhang** [comment]
This means there is an error in your input file. Could you paste the content of your input file here?

**Comment by BW15061999** [comment]
Hi, here is a part of the `input.yml`, and the `fastq.gz` files are from fastq-dump
```
ATAC-seq:
  - id: Tmem
    group: Tmem
    replicates:
      - rep: 1
        files:
          - path: Taiji/scar/input/SRR11776866_1.fastq.gz
          - path: Taiji/scar/input/SRR11776866_2.fastq.gz
            tags: ['PairedEnd']
      - rep: 2
        files:
          - path: Taiji/scar/input/SRR11776867_1.fastq.gz
          - path: Taiji/scar/input/SRR11776867_2.fastq.gz
            tags: ['PairedEnd']

```

**Comment by kaizhang** [comment]
If you have two paired files, you need to use the `pair` keyword, like this:

```
ATAC-seq:
  - id: Tmem
    group: Tmem
    replicates:
      - rep: 1
        files:
          - pair:
            - path: Taiji/scar/input/SRR11776866_1.fastq.gz
            - path: Taiji/scar/input/SRR11776866_2.fastq.gz
      - rep: 2
        files:
          - pair:
            - path: Taiji/scar/input/SRR11776867_1.fastq.gz
            - path: Taiji/scar/input/SRR11776867_2.fastq.gz
```
