### ISSUE TITLE
input file

### ISSUE THREAD

**Issue by Mlad22** [Taiji-pipeline/Taiji#3]
Hello, 

If I have fastq.gz ATACseq files from different reads or different sequencing lanes, how do I specify this in the input tsv file?

Thanks for the help.

Best,
mlad

**Comment by kaizhang** [comment]
To input paired end reads:

For YAML format, you can use:

```
ATAC-Seq:
- group: groupname
  id: expid
  replicates:
  - rep: 1
    files:
      - pair:
        - path: R1.fq.gz
        - path: R2.fq.gz
```

For TSV format, you can use:

```
type	id	group	rep	path
ATAC-seq	expid	groupname	1	R1.fq.gz,R2.fq.gz
```

For reads from multiple lanes, you need to combine them first before inputting them to Taiji. This is easy to do:

```
cat lane1.fq.gz lane2.fq.gz lane3.fq.gz > combine.fq.gz
```
