### ISSUE TITLE
Error. Failed: Could not find transcript_id

### ISSUE THREAD

**Issue by jrose835** [Taiji-pipeline/Taiji#30]
Hello,

I am having trouble running taiji (v1.2.1.3) on some human RNAseq/ATACseq data which ends with this error:

```
[ERROR][07-29 18:51] ^[[0m^[[0m^[[31mRNA_Convert_ID_To_Name(deb6..) Failed: could not find "transcript_id"
CallStack (from HasCallStack):
  error, called at src/Bio/RealWorld/GENCODE.hs:96:26 in bioinformatics-toolkit-0.9.5-3mVlLPWw5KFJ8YTMh3VDIA:Bio.RealWorld.GENCODE
CallStack (from HasCallStack):
  error, called at src/Control/Workflow/Interpreter/Exec.hs:143:37 in SciFlow-0.7.2-TntpNqG8TaLOeICwjTwEt:Control.Workflow.Interpreter.Exec
```

After double-checking my input and config files (pasted below), I still can't seem to figure out what is causing this error. Any advice would be very helpful. 

Thank you!

**Code run:**
`taiji run --config config.yml`

**Input.yml**
```
ATAC-Seq:
  - id: SLE_rN_highDA_ATAC
    group: SLE_rN_highDA
    replicates:
      - rep: 1
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/SLE.1929.1537.rN/SLE.1929.1537.rN.MACS2.Peaks/SLE.1929.1537.rN_peaks.narrowPeak
            format: NarrowPeak
      - rep: 2
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/SLE.1551.1597.rN/SLE.1551.1597.rN.MACS2.Peaks/SLE.1551.1597.rN_peaks.narrowPeak
            format: NarrowPeak
      - rep: 3
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/SLE.1731.1738.rN/SLE.1731.1738.rN.MACS2.Peaks/SLE.1731.1738.rN_peaks.narrowPeak
            format: NarrowPeak
      - rep: 4
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/SLE.2711.871.rN/SLE.2711.871.rN.MACS2.Peaks/SLE.2711.871.rN_peaks.narrowPeak
            format: NarrowPeak
      - rep: 5
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/SLE.3202.2491.rN/SLE.3202.2491.rN.MACS2.Peaks/SLE.3202.2491.rN_peaks.narrowPeak
            format: NarrowPeak

  - id: SLE_T1T2_highDA_ATAC
    group: SLE_T1T2_highDA
    replicates:
      - rep: 1
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/SLE.1929.1537.T1-2/SLE.1929.1537.T1-2.MACS2.Peaks/SLE.1929.1537.T1-2_peaks.narrowPeak
            format: NarrowPeak

  - id: HC_rN_NA_ATAC
    group: HC_rN_NA
    replicates:
      - rep: 1
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/HCD.918.1215.rN/HCD.918.1215.rN.MACS2.Peaks/HCD.918.1215.rN_peaks.narrowPeak
            format: NarrowPeak
      - rep: 2
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/HCD.646.1234.rN/HCD.646.1234.rN.MACS2.Peaks/HCD.646.1234.rN_peaks.narrowPeak
            format: NarrowPeak
      - rep: 3
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/HCD.796.1235.rN/HCD.796.1235.rN.MACS2.Peaks/HCD.796.1235.rN_peaks.narrowPeak
            format: NarrowPeak
     - rep: 4
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/HCD.1171.1296.rN/HCD.1171.1296.rN.MACS2.Peaks/HCD.1171.1296.rN_peaks.narrowPeak
            format: NarrowPeak
      - rep: 5
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/HCD.878.1606.rN/HCD.878.1606.rN.MACS2.Peaks/HCD.878.1606.rN_peaks.narrowPeak
            format: NarrowPeak
      - rep: 6
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/HCD.875.1610.rN/HCD.875.1610.rN.MACS2.Peaks/HCD.875.1610.rN_peaks.narrowPeak
            format: NarrowPeak

  - id: HC_T1T2_NA_ATAC
    group: HC_T1T2_NA
    replicates:
      - rep: 1
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/HCD.918.1215.T1-2/HCD.918.1215.T1-2.MACS2.Peaks/HCD.918.1215.T1-2_peaks.narrowPeak
            format: NarrowPeak
      - rep: 2
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/HCD.646.1234.T1-2/HCD.646.1234.T1-2.MACS2.Peaks/HCD.646.1234.T1-2_peaks.narrowPeak
            format: NarrowPeak
      - rep: 3
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/HCD.1171.1296.T1-2/HCD.1171.1296.T1-2.MACS2.Peaks/HCD.1171.1296.T1-2_peaks.narrowPeak
            format: NarrowPeak
      - rep: 4
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/HCD.875.1610.T1-2/HCD.875.1610.T1-2.MACS2.Peaks/HCD.875.1610.T1-2_peaks.narrowPeak
            format: NarrowPeak

  - id: SLE_rN_lowDA_ATAC
    group: SLE_rN_lowDA
    replicates:
      - rep: 1
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/SLE.2913.559.rN/SLE.2913.559.rN.MACS2.Peaks/SLE.2913.559.rN_peaks.narrowPeak
            format: NarrowPeak
      - rep: 2
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/SLE.2911.2209.rN/SLE.2911.2209.rN.MACS2.Peaks/SLE.2911.2209.rN_peaks.narrowPeak
            format: NarrowPeak
      - rep: 3
       files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/SLE.2932.3240.rN/SLE.2932.3240.rN.MACS2.Peaks/SLE.2932.3240.rN_peaks.narrowPeak
            format: NarrowPeak
      - rep: 4
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/SLE.3136.3378.rN/SLE.3136.3378.rN.MACS2.Peaks/SLE.3136.3378.rN_peaks.narrowPeak
            format: NarrowPeak
      - rep: 5
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/SLE.2891.420.rN/SLE.2891.420.rN.MACS2.Peaks/SLE.2891.420.rN_peaks.narrowPeak
            format: NarrowPeak
      - rep: 6
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/SLE.2880.3039.rN/SLE.2880.3039.rN.MACS2.Peaks/SLE.2880.3039.rN_peaks.narrowPeak
            format: NarrowPeak
      - rep: 7
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/SLE.2900.3328.rN/SLE.2900.3328.rN.MACS2.Peaks/SLE.2900.3328.rN_peaks.narrowPeak
            format: NarrowPeak
      - rep: 8
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/SLE.2898.3314.rN/SLE.2898.3314.rN.MACS2.Peaks/SLE.2898.3314.rN_peaks.narrowPeak
            format: NarrowPeak

  - id: SLE_T1T2_lowDA_ATAC
    group: SLE_T1T2_lowDA
    replicates:
      - rep: 1
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/SLE.2913.559.T1-2/SLE.2913.559.T1-2.MACS2.Peaks/SLE.2913.559.T1-2_peaks.narrowPeak
            format: NarrowPeak
      - rep: 2
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/SLE.2911.2209.T1-2/SLE.2911.2209.T1-2.MACS2.Peaks/SLE.2911.2209.T1-2_peaks.narrowPeak
            format: NarrowPeak
      - rep: 3
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/SLE.2891.420.T1-2/SLE.2891.420.T1-2.MACS2.Peaks/SLE.2891.420.T1-2_peaks.narrowPeak
            format: NarrowPeak
      - rep: 4
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/data/SLE.2900.3328.T1-2/SLE.2900.3328.T1-2.MACS2.Peaks/SLE.2900.3328.T1-2_peaks.narrowPeak
            format: NarrowPeak

RNA-Seq:
  - id: SLE_rN_highDA_RNA
    group: SLE_rN_highDA
    replicates:
      - rep: 1
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.0.3621.rN/SLE.0.3621.rN.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 2
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.0.1537.rN/SLE.0.1537.rN.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 3
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.0.1597.rN/SLE.0.1597.rN.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 4
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.0.1738.rN/SLE.0.1738.rN.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 5
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.2711.871.rN/SLE.2711.871.rN.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 6
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.3202.2491.rN/SLE.3202.2491.rN.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 7
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.3039.3553.rN/SLE.3039.3553.rN.rpkm.tsv
            tags: ['GeneQuant']

  - id: SLE_T1T2_highDA_RNA
    group: SLE_T1T2_highDA
    replicates:
      - rep: 1
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.0.3651.T1T2/SLE.0.3651.T1T2.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 2
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.0.1537.T1T2/SLE.0.1537.T1T2.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 3
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.0.1597.T1T2/SLE.0.1597.T1T2.rpkm.tsv
            tags: ['GeneQuant']
    - rep: 4
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.0.1738.T1T2/SLE.0.1738.T1T2.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 5
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.2711.871.T1T2/SLE.2711.871.T1T2.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 6
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.3202.2491.T1T2/SLE.3202.2491.T1T2.rpkm.tsv
            tags: ['GeneQuant']

  - id: HC_rN_NA_RNA
    group: HC_rN_NA
    replicates:
      - rep: 1
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/HCD.918.1215.rN/HCD.918.1215.rN.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 2
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/HCD.646.1234.rN/HCD.646.1234.rN.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 3
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/HCD.796.1235.rN/HCD.796.1235.rN.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 4
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/HCD.1171.1296.rN/HCD.1171.1296.rN.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 5
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/HCD.878.1606.rN/HCD.878.1606.rN.rpkm.tsv
            tags: ['GeneQuant']

  - id: HC_T1T2_NA_RNA
    group: HC_T1T2_NA
    replicates:
      - rep: 1
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/HCD.918.1215.T1T2/HCD.918.1215.T1T2.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 2
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/HCD.646.1234.T1T2/HCD.646.1234.T1T2.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 3
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/HCD.796.1235.T1T2/HCD.796.1235.T1T2.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 4
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/HCD.1171.1296.T1T2/HCD.1171.1296.T1T2.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 5
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/HCD.878.1606.T1T2/HCD.878.1606.T1T2.rpkm.tsv
            tags: ['GeneQuant']

  - id: SLE_rN_lowDA_RNA
    group: SLE_rN_lowDA
    replicates:
      - rep: 1
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.2913.559.rN/SLE.2913.559.rN.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 2
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.2911.2209.rN/SLE.2911.2209.rN.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 3
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.2932.3240.rN/SLE.2932.3240.rN.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 4
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.3136.3378.rN/SLE.3136.3378.rN.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 5
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.2891.420.rN/SLE.2891.420.rN.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 6
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.2880.3039.rN/SLE.2880.3039.rN.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 7
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.2900.3328.rN/SLE.2900.3328.rN.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 8
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.2898.3314.rN/SLE.2898.3314.rN.rpkm.tsv
            tags: ['GeneQuant']
     - rep: 9
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.2893.428.rN/SLE.2893.428.rN.rpkm.tsv
            tags: ['GeneQuant']

  - id: SLE_T1T2_lowDA_RNA
    group: SLE_T1T2_lowDA
    replicates:
      - rep: 1
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.2913.559.T1T2/SLE.2913.559.T1T2.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 2
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.2911.2209.T1T2/SLE.2911.2209.T1T2.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 3
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.2932.3240.T1T2/SLE.2932.3240.T1T2.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 4
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.3136.3378.T1T2/SLE.3136.3378.T1T2.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 5
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.2891.420.T1T2/SLE.2891.420.T1T2.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 6
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.2880.3039.T1T2/SLE.2880.3039.T1T2.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 7
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.2900.3328.T1T2/SLE.2900.3328.T1T2.rpkm.tsv
            tags: ['GeneQuant']
      - rep: 8
        files:
          - path: /home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_RNA/data2/SLE.2898.3314.T1T2/SLE.2898.3314.T1T2.rpkm.tsv
            tags: ['GeneQuant']

```

**config.yml**
```
################################################################################
# The meaning of each field is explained at:
# https://taiji-pipeline.github.io/documentation/options.html
################################################################################

################################################################################
# Minimal settings
################################################################################

input: "input.yml"

output_dir: "/home/boss_lab/Projects/ACE_Collaborations/AutoimmuneDisease_rN_T12/ACE_rN_T12_ATAC/ATAC_concat/analysis/PageRank/run2_JR/output/"

# Replace, this will download the genome into the output directory
# Options: mm10, hg38, GRCh38, GRCm38
#assembly: "mm10" # Replace, this will download the genome into the output directory

################################################################################
# Advanced settings
################################################################################

# Replace, options: HG38.nohap.fa hg38.eGFP.fa lambda.J02459.1.fa mm10.fa mm10_ERCC.fa rn6.ERCC.fa phiX174.fa 
genome: "/home/boss_lab/Apps/genomes/fasta/HG38.nohap.fa"

# Replace, options: hg38_gencodeV27.gtf mm10.gencode.vM17.gtf rn6.refGene.gtf
annotation: "/home/boss_lab/Apps/genomes/fasta/hg38_gencodeV27.gtf"

# Replace, options: cisBP_mouse.meme, cisBP_human.meme
motif_file: "/home/boss_lab/Apps/bitbucket/pagerank/taiji-1.2.1.3-formatting/cisBP_human.meme"

# TODO
#genome_index: ""

# Replace, options: HG38.nohap hg38.eGFP mm10.ERCC rn6.ERCC
bwa_index: "/home/boss_lab/Apps/genomes/bwa/HG38.nohap"

# Replace, options: hg38.ERCC.STAR-2.7.0f hg38.nohap hg38.nohap.ERCC.eGFP index_scripts mm10.ERCC rn6.ERCC
#star_index: "/home/boss_lab/Apps/genomes/STAR/hg38.nohap"

#rsem_index: ""

#callpeak_fdr: 0.01

#callpeak_genome_size: "" # options: hs

#tss_enrichment_cutoff: 5

```

**System info:**
Taiji-v1.2.1.3
Linux
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
