### ISSUE TITLE
QeneQuant raw reads vs normalized

### ISSUE THREAD

**Issue by davidsanin** [Taiji-pipeline/Taiji#39]
Hi! Thanks for the cool tool!
When I start from estimated read counts from a different pipeline (STAR > featureCounts) should I provide Taiji with raw reads or should I normalise them somehow before running?

My input looked like this and everything went smoothly.

```
ATAC-seq:
  - id: Naive_ATAC
    group: Naive
    replicates:
      - rep: 1
        files:
          - path: /ATAC/Naive_1.short.cleaned.bam
            tags: ['PairedEnd']

RNA-seq:
  - id: Naive_RNA
    group: Naive
    replicates:
      - rep: 1
        files:
          - path: /RNA_counts/Naive_1.tsv
            tags: ['GeneQuant']
```

Also my ATAC BAM files were pre-filtered (removed duplicates and longer fragments). Should I add the "Filtered" tag to it? 
I just wanted to make sure I was not missing something! Thanks!!
